// <auto-generated />
using System;
using Common.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20241010171259_MergeFieldsCommit")]
    partial class MergeFieldsCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Build", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Changed")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitId")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ErrorLogs")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime?>("Queued")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Changed");

                    b.HasIndex("CommitId");

                    b.ToTable("Builds", (string)null);
                });

            modelBuilder.Entity("Common.Models.Commit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("JiraCardID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("AuthorName");

                    b.ToTable("Commits", (string)null);
                });

            modelBuilder.Entity("Pipeline", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastBuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSuccessfulBuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastBuildId");

                    b.HasIndex("LastSuccessfulBuildId");

                    b.ToTable("Pipelines", (string)null);
                });

            modelBuilder.Entity("Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("MasterClonned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int?>("PipelineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PipelineId");

                    b.HasIndex("Project");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("Build", b =>
                {
                    b.HasOne("Common.Models.Commit", "Commit")
                        .WithMany()
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("Pipeline", b =>
                {
                    b.HasOne("Build", "Last")
                        .WithMany()
                        .HasForeignKey("LastBuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Build", "LastSuccessful")
                        .WithMany()
                        .HasForeignKey("LastSuccessfulBuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Last");

                    b.Navigation("LastSuccessful");
                });

            modelBuilder.Entity("Repository", b =>
                {
                    b.HasOne("Pipeline", "Pipeline")
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pipeline");
                });
#pragma warning restore 612, 618
        }
    }
}
