name: Electronize Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj', '**/global.json') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Cache .NET tools
      uses: actions/cache@v3
      with:
        path: ~/.dotnet/tools
        key: dotnet-tools-${{ runner.os }}-${{ hashFiles('**/global.json') }}
        restore-keys: |
          dotnet-tools-${{ runner.os }}-

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Adjust the version according to your project requirements

    - name: Install ElectronNET.CLI
      run: dotnet tool install ElectronNET.CLI --global

    - name: Restore dependencies
      run: dotnet restore Front2

    - name: Build with Electronize
      run: |
        cd Front2
        electronize build /target win

    - name: Upload .exe Artifact
      uses: actions/upload-artifact@v3
      with:
        name: electron-build-exe
        path: |
          Front2/bin/Desktop/*.exe
