name: Electronize Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Adjust the version according to your project requirements

    - name: Install ElectronNET.CLI
      run: dotnet tool install ElectronNET.CLI --global

    - name: Restore dependencies
      run: dotnet restore Front2

    - name: Build with Electronize
      run: |
        cd Front2
        electronize build /target win

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-build
        path: |
          Front2/bin/desktop/win
